# agents/procurement_agent.py
"""
Procurement Advisor Agent

- Orchestrates numeric procurement suggestions generated by crud.get_procurement_suggestions(...)
- For each suggestion, calls an LLM (OpenAI or OpenRouter) to produce a short human-friendly explanation.
- Exposes run_procurement_advisor(project_id, lookback_days) which returns the numeric suggestions + `ai_explanation` text for each item.

Environment:
- Use OPENAI_API_KEY for OpenAI (via openai Python package)
- Or use OPENROUTER_API_KEY for OpenRouter (HTTP call)
- Optionally set OPENAI_MODEL_NAME or OPENROUTER_MODEL_NAME to choose model (defaults provided)

Notes:
- LLM is used only to *explain* numeric suggestions (not to compute them).
- Temperature is low (0.2) for deterministic outputs.
"""

from datetime import datetime
import json
import os
import traceback
from typing import Dict, Any

# Local DB & helpers
from database import SessionLocal
from crud import get_procurement_suggestions

# LLM libraries
import requests
import openai

# Load environment variables (if using python-dotenv in your app, it should already be loaded)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME", "gpt-4o-mini")  # change if you want

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL_NAME = os.getenv("OPENROUTER_MODEL_NAME", "gpt-4o-mini")  # example; set per your OpenRouter model

# Configure OpenAI library if available
if OPENAI_API_KEY:
    openai.api_key = OPENAI_API_KEY


def _llm_call_openai(system_prompt: str, user_prompt: str, max_tokens: int = 400, temperature: float = 0.2, model: str = None) -> str:
    """
    Use openai.ChatCompletion to get a reply. Returns text or raises Exception.
    """
    model = model or OPENAI_MODEL_NAME or "gpt-4o-mini"
    resp = openai.ChatCompletion.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        max_tokens=max_tokens,
        temperature=temperature,
    )
    # extract text reliably
    if resp and getattr(resp, "choices", None):
        choice = resp.choices[0]
        # For ChatCompletion, the reply is in choice.message.content
        if hasattr(choice, "message") and isinstance(choice.message, dict):
            return choice.message.get("content", "").strip()
        # fallback
        return choice.get("text", "").strip()
    return ""


def _llm_call_openrouter(system_prompt: str, user_prompt: str, max_tokens: int = 400, temperature: float = 0.2, model: str = None) -> str:
    """
    Call OpenRouter chat completions endpoint.
    Endpoint: https://api.openrouter.ai/v1/chat/completions
    Returns text or raises Exception.
    """
    model = model or OPENROUTER_MODEL_NAME or "gpt-4o-mini"
    url = "https://api.openrouter.ai/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "max_tokens": max_tokens,
        "temperature": temperature,
    }
    r = requests.post(url, headers=headers, json=payload, timeout=30)
    r.raise_for_status()
    j = r.json()
    # parse first choice
    if "choices" in j and len(j["choices"]) > 0:
        ch = j["choices"][0]
        # Chat-format: ch["message"]["content"]
        if "message" in ch and isinstance(ch["message"], dict) and "content" in ch["message"]:
            return ch["message"]["content"].strip()
        # else maybe "text"
        if "text" in ch:
            return ch["text"].strip()
    # fallback
    return json.dumps(j)


def call_llm_explanation(suggestion_summary: Dict[str, Any]) -> str:
    """
    Call an LLM to produce a clear procurement explanation for suggestion_summary.
    We try providers in this order: OPENAI, OPENROUTER. If none configured, fallback to template text.

    suggestion_summary: small dict with numeric fields:
      { material_id, material_name, current_quantity, days_of_stock, reorder_point, safety_stock, recommended_order_qty, top_suppliers }
    """
    system = (
        "You are an expert procurement assistant. You will be given a small JSON describing a material's current "
        "stock, estimated demand and recommended order quantity. Produce a short (2-3 sentences) human-friendly "
        "explanation and a one-line actionable recommendation for a site procurement manager. "
        "Be concise, avoid making up numbers not provided, and if data is missing tell the user what is missing and how to obtain it."
    )

    # provide a compact but explicit user prompt with the numeric data
    user = "Here is the data (JSON):\n" + json.dumps(suggestion_summary, indent=2, default=str)

    # Try OpenAI if key present
    try:
        if OPENAI_API_KEY:
            return _llm_call_openai(system, user, max_tokens=420, temperature=0.2)
    except Exception as e:
        # log and fallback
        print("OpenAI call failed:", e)
        print(traceback.format_exc())

    # Try OpenRouter if key present
    try:
        if OPENROUTER_API_KEY:
            return _llm_call_openrouter(system, user, max_tokens=420, temperature=0.2)
    except Exception as e:
        print("OpenRouter call failed:", e)
        print(traceback.format_exc())

    # Fallback deterministic explanation
    try:
        material = suggestion_summary.get("material_name", "Material")
        rq = suggestion_summary.get("recommended_order_qty")
        rp = suggestion_summary.get("reorder_point")
        ss = suggestion_summary.get("safety_stock")
        cur = suggestion_summary.get("current_quantity")
        suppliers = suggestion_summary.get("top_suppliers", [])
        supplier_line = ""
        if suppliers:
            top = suppliers[0]
            supplier_line = f"Top supplier candidate: {top.get('supplier_name')} (lead {top.get('lead_time_days')}d, score {top.get('score')})."
        expl = (
            f"{material}: Current stock {cur}. Recommended order qty: {rq}. Reorder point: {rp}. Safety stock: {ss}. "
            f"{supplier_line} If data is missing (unit price or lead time), gather recent cost records or contact suppliers for quotes."
        )
        return expl
    except Exception:
        return "Procurement explanation currently unavailable."


# --- Public entrypoint used by FastAPI ---
def run_procurement_advisor(project_id: int, lookback_days: int = 90):
    """
    Main function: fetch numeric suggestions, call LLM to annotate each suggestion with an `ai_explanation`,
    and return a result dict.

    Returns:
      {
        "project_id": <>,
        "project_name": "<>",
        "generated_at": "<iso>",
        "suggestions": [ { ... , "ai_explanation": "..." }, ... ]
      }
    """
    db = SessionLocal()
    try:
        numeric = get_procurement_suggestions(db, project_id, lookback_days=lookback_days)
        # For readability / smaller LLM prompts, we'll include only top suppliers info (top 3)
        for s in numeric.get("suggestions", []):
            summary = {
                "material_id": s.get("material_id"),
                "material_name": s.get("material_name"),
                "current_quantity": s.get("current_quantity"),
                "days_of_stock": s.get("days_of_stock"),
                "reorder_point": s.get("reorder_point"),
                "safety_stock": s.get("safety_stock"),
                "recommended_order_qty": s.get("recommended_order_qty"),
                "top_suppliers": s.get("supplier_scores", [])[:3]
            }
            try:
                explanation = call_llm_explanation(summary)
            except Exception as e:
                print(f"LLM explanation failed for material {s.get('material_name')}: {e}")
                explanation = "AI explanation currently unavailable."
            s["ai_explanation"] = explanation
        numeric["generated_at"] = datetime.utcnow().isoformat()
        return numeric
    finally:
        db.close()
